name: Deploy to Cloud Run

# Trigger this workflow on pushes to the main branch
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
    # 1) Check out your repository
    - name: Checkout code
      uses: actions/checkout@v3

    # 2) Authenticate to Google Cloud using the service account key
    - name: Google Cloud Authentication
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    # 3) Install & configure gcloud
    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ steps.auth.outputs.project_id }}

    # 4) Deploy your app to Cloud Run using Buildpacks
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ada-analytics \
          --source . \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated